### ISSUE TITLE
loo.stanreg doesn't handle weights properly

### ISSUE THREAD

**Issue by enbrown** [stan-dev/rstanarm#106]
#### Summary:
`loo` with `k_threshold` defined doesn't handle regression with weights.

#### Description:
If a regression (as simple as `stan_lm()`) is called with weights and a subsequent call to `loo()` then requires re-fitting the model to leave out observations (because of setting the `k_threshold` argument), then an error is thrown. The function `reloo()` in `R/loo.R` calls `fit_j <- suppressWarnings(update(x, data = d[-omitted, ], refresh = 0))` which excludes the omitted observation from the `data` argument but not the `weights` argument to `update()`.

#### Reproducible Steps:
```r
data("clouds", package = "HSAUR3")
post <- stan_lm(rainfall ~ seeding * (sne + cloudcover + prewetness + echomotion) + time,
    data = clouds,
    weights = rep(1:2, 12),
    prior = R2(location = 0.2), seed = 1)
loo(post, k_threshold = 0.7)
```

#### RStanARM Version:
2.9.0.5

#### R Version:
3.3.0

#### Operating System:
Fedora 23

**Comment by jgabry** [comment]
Thanks for reporting this and for the good description of the where the
problem occurs.

It should be easy from a coding perspective to fix this so that weights[i]
is dropped when observation i is dropped, but I think we need to think a
bit more about when/if it's appropriate to use loo with models that have
weights. @bgoodri any thoughts on this?

And even beyond loo, there are a couple of reasons why it's not
even entirely correct to allow these kinds of weights at all in a Bayesian
model, but given that we are allowing them we should be clear about when
they are and are not recommended and which of the functions in the package
will work with weights and which won't.

**Comment by bgoodri** [comment]
I doubt the weights are appropriate to begin with, but we certainly don't know if the model with the smallest LOOIC is consistent for the model with the highest ELPD for future data when weights are involved. It seems like you would need to know what weight to apply to the future data when calculating the ELPD. So, I think `loo` should error with a suggestion to call `kfold` with `K = 1` when weights were used.

**Comment by jgabry** [comment]
On Wednesday, July 6, 2016, bgoodri <notifications@github.com> wrote:

> I doubt the weights are appropriate to begin with, but we certainly don't
> know if the model with the smallest LOOIC is consistent for the model with
> the highest ELPD for future data when weights are involved. It seems like
> you would need to know what weight to apply to the future data when
> calculating the ELPD.
>
Yeah that seems right.

>  So, I think loo should error with a suggestion to call kfold with K = 1
> when weights were used.
>
Why would K=1 be useful?

**Comment by jgabry** [comment]
In fact I think we should require `K > 1`, as `K=1` essentially says make 1 subset to leave out, which is to say, leave out _all_ of the data.

**Comment by bgoodri** [comment]
I meant K=N.
