### ISSUE TITLE
option to access full posterior of derived quantities

### ISSUE THREAD

**Issue by davharris** [stan-dev/rstanarm#121]
#### Summary:

A number of useful model statistics are available as point estimates from `stanreg` objects, but it isn't clear how best to obtain the full posterior for many of these values.  Examples include most of the functions listed under `stanreg-methods`, e.g. `fitted`, `residuals`, `VarCorr`, etc.

Assuming that I'm not just missing something obvious, it would be helpful if the `stanreg` methods had a flag that caused them to return the full posterior instead of point estimates.
#### RStanARM Version:

2.12.1
#### R Version:

3.3.1
#### Operating System:

10.12.0

**Comment by bgoodri** [comment]
Functions like `fitted`, `residuals`, and `VarCorr` are really more intended for a quick glance. We want to steer people toward using `posterior_predict`, in which case you can do pretty much whatever you want and have the option of using a random subset of the draws. There is also `posterior_linpred` which is more practical in some circumstances.

**Comment by davharris** [comment]
Ah, `posterior_linpred` helps a lot.  I can get fitted/residuals/etc from that.

What's the best way to get the posterior for the variance associated with varying effects? It doesn't seem to be stored explicitly as a parameter.

Thanks for the quick response.

**Comment by bgoodri** [comment]
It is correct that the hypervariances are not stored, which came up in
https://github.com/stan-dev/rstanarm/issues/112 and involves similar
concerns. We don't encourage things like

res <- -sweep(posterior_linpred(post), MARGIN = 2, stats = y, FUN = `-`)

to calculate "residuals" because the res object doesn't correspond to a
valid Bayesian concept. Conversely,

err <- -sweep(posterior_predict(post), MARGIN = 2, stats = y, FUN = `-`)

corresponds to a valid Bayesian concept --- the distribution of the
differences between observations and the model's prediction of them --- but
it isn't really comparable to frequentist "residuals". It is the posterior
predictive distribution of "errors".

**Comment by davharris** [comment]
Maybe. It's also possible that you haven't considered the full range of "valid" analyses. Thanks for your help.

**Comment by jgabry** [comment]
On Friday, September 30, 2016, David J. Harris <notifications@github.com>
wrote:

> Maybe. It's also possible that you haven't considered the full range of
> "valid" analyses. Thanks for your help.
>
Hi David, yes that's certainly possible!

Do you have an example of an analysis with rstanarm for which looking at
the full distribution of residuals computed using the linear predictor
would be useful or more useful than residuals computed from the posterior
predictive distribution?

Jonah

>

**Comment by davharris** [comment]
The model was basically `y ~ (1 | subject_id) + (1 | observer_id)`.

Each subject was observed 20 times in succession, often by a mix of observers with different biases.  The scientific/statistical question I wanted to answer was whether there was autocorrelation in the repeated observations, after accounting for the biases introduced by observer effects. I don't see any reason why asking this question would make me a bad Bayesian.

If we write the model as`y_ij = grand_mean + subject_mean_i + observer_mean_ij + noise_ij`, then this question seems to require the `noise_ij` values, or at least `y_ij - observer_mean_ij`.

**Comment by betanalpha** [comment]
It makes you a bad Bayesian because you’re not modeling
autocorrelation!  If you think there is time-dependent effects
then model them explicitly and see if the autocorrelation
is consistent with zero or not.  Alternatively you could look
for empirical autocorrelation in some posterior predictive
statistic (i.e. fancy way of checking for autocorrelation in
the residuals) but then that brings you back to what Jonah
was recommending.

Trying to look for autocorrelation in the _parameters_
is tricky to interpret and hence can lead to awkward
results.

**Comment by davharris** [comment]
The idea that checking residuals for unwanted patterns makes someone a "bad Bayesian" would be news to a lot of Bayesians ([including someone you might know](http://www.stat.columbia.edu/~gelman/research/published/p755.pdf)).

**Comment by jgabry** [comment]
I haven't read that paper in a while, but if I remember correctly it's
recommending the residuals y - y_rep, right? That is, observed data vs
simulations from the model. That's exactly the type of residuals we
_are_ recommending (and what the pp_check function plots with check =
"resid"). Sorry if that was unclear from what I wrote before.

(Even if I'm wrong about that paper, it's from at least a decade ago
and the author has been known to revise his recommendations to reflect more
recent research (e.g. he used to recommend non-informative priors but not
so much anymore).)

**Comment by bgoodri** [comment]
Except that "we" are (or at least I am) trying not to call y - y_rep a "residual". It is really an "error", or a "predictive error" if you like.

**Comment by jgabry** [comment]
Yeah perhaps we need to be more clear about that, because in the pp_check
doc and elsewhere I refer to them as residuals (because Andrew I guess),
but it's true that  in-sample predictive errors is more appropriate if it's
y - y_rep.

**Comment by betanalpha** [comment]
Please reread my comment.  I never said that residual analysis was
bad, but rather that you have to do it on proper posterior predictive
statistics and not intermediate parameters.

**Comment by jgabry** [comment]
On Monday, October 3, 2016, David J. Harris <notifications@github.com>
wrote:

> The model was basically y ~ (1 | subject_id) + (1 | observer_id).
>
> Each subject was observed 20 times in succession, often by a mix of
> observers with different biases. The scientific/statistical question I
> wanted to answer was whether there was autocorrelation in the repeated
> observations, after accounting for the biases introduced by observer
> effects. I don't see any reason why asking this question would make me a
> bad Bayesian.
>
> If we write the model asy_ij = grand_mean + subject_mean_i +
> observer_mean_ij + noise_ij, then this question seems to require the
> noise_ij values, or at least y_ij - observer_mean_ij.
>
To bring it back to your particular model: if this is the model that has
been fit, then, assuming a Gaussian DGP, looking at something like
residuals on the outcome scale is fine. But y - y_hat is the classical
residual (even if y_hat was computed from a Bayesian model). For the
uncertainty to be properly propagated into the comparison, the Bayesian
version would be a posterior predictive residual (or really, as Ben
says,  prediction error) y - y_tilde, where y_tilde is from the posterior
predictive distribution of the outcome implied by the model. Andrew would
call y_tilde y_rep (because it's in-sample). So I don't think
anyone responding on this thread thinks residuals (in the sense
of in-sample prediction errors described above) are wrong or
always useless. We may have been talking past each other. I think Michael,
Ben, and I have just been saying what I said above, which is what you said
with the addition of the posterior predictive distribution. Sorry for any
confusion.

Jonah

**Comment by jgabry** [comment]
Closing this because I think the latest release resolves this. Posterior draws of hierarchical sd (and covariance) parameters are now accessible (see #112 for an example). Also relevant to various things discussed in this thread is the new `predictive_error` function.
