### ISSUE TITLE
`print.stanreg` shows num unconstrained pars but not explained anywhere

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#148]
At some point the number of unconstrained parameters was added to the output from `print.stanreg`, but the meaning of this number is not obvious and is not really explained at all. If the target audience of rstanarm is what we say it is then we shouldn't have things like this that are printed every time a model is fit but not explained anywhere. I think it should either (a) be explained (probably in the doc for `print.stanreg`) or (b) we should just say "parameters" instead of "unconstrained parameters" (even if incorrect). @bgoodri I'm fine with either (a) or (b), so whichever you prefer.

**Comment by bgoodri** [comment]
I was in favor of (c): not mentioning it. But it was Andrew who wanted it
in `print.stanreg` in order to help remember what model he estimated.
Unfortunately, other rstanarm users will interpret it as the model
complexity, particularly if we call it parameters rather than unconstrained
parameters. I guess (a) would be second best if we just document it as a
meaningless quantity and that you should call loo() to see the number of
effective parameters.

**Comment by jgabry** [comment]
I'll send an email to A first so we don't end up changing this multiple
times.

**Comment by jgabry** [comment]
Ok seems like (c) has now been sanctioned. I'll remove it and then close this.

**Comment by bgoodri** [comment]
Good

**Comment by jgabry** [comment]
Do you still want to print the number of observations? That was on the same line as the number of unconstrained parameters. The number of observations is included in `summary.stanreg` output and accessible via `nobs(fit)`, so I'm not sure we need in `print.stanreg` too. But it's not misleading so I'm not opposed to keeping it if you want.

**Comment by jgabry** [comment]
I dropped the number of observations too. Can add it back if you want, but it doesn't seem necessary for `print.stanreg` when it's accessible in two other easy ways

**Comment by bgoodri** [comment]
OK
