### ISSUE TITLE
Reorganize unit tests

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#175]
#### Summary:

The current unit tests are too duplicative and take too much time to run. We should reorganize most of them so that a file estimates a particular model and then tests `posterior_predict`, `loo`, etc.

#### Description:

Take test_loo.R for example. It has a "test that loo/waic for stan_glm works", which estimates six Stan models that are already being estimated elsewhere in the test suite. We should have

- test_gaussian.R
- test_binomial.R
- test_poisson.R
- test_negbin.R
- test_gamma.R
- test_inverse_gaussian.R

etc. that each obtain a reasonable number of draws from a posterior distribution once and then test that all the post-estimation things work.

#### Reproducible Steps:

Look at the tests

#### RStanARM Version:

2.14.1

#### R Version:

3.3.3

#### Operating System:

Debian

**Comment by jgabry** [comment]
Totally agree. Unfortunately this in itself isn't what's contributing to the travis builds timing out. I think that's mostly compilation time.

**Comment by bgoodri** [comment]
Yeah, I am more worried about staying on CRAN's good side. They are more
tolerant of long installation time than long examples / vignettes / unit
tests.

**Comment by jgabry** [comment]
I can work on this, but quick question first. It looks like you want to test by "family" rather than modeling function, is that correct? For example, would `test_gaussian.R` include models fit using each of `stan_aov`, `stan_lm`, `stan_glm`, `stan_glmer`, `stan_gamm4`?

**Comment by jgabry** [comment]
Also, would we fit a model using each allowed link function for each family+modeling-function combination?

**Comment by jgabry** [comment]
Actually, there are a bunch of things to decide. I'm including my two questions from above plus some others here: 

* It looks like you want to test by "family" rather than modeling function, is that correct? For example, would test_gaussian.R include models fit using each of stan_aov, stan_lm, stan_glm, stan_glmer, stan_gamm4?

* would we still fit a model using each allowed link function for each family+modeling-function combination?

* would each file contain tests for MCMC, optimization, and VB or would we separate those into additional files? 

* where would we test for correct errors, warnings, and messages? Those are function-specific not model specified.

**Comment by bgoodri** [comment]
I don't know that we need to try hard to fit a model with every link
function (because some of them are odd), but we should at least verify that
it runs 1 iteration with every link function.

**Comment by bgoodri** [comment]
We could test by modeling function I guess. Not sure which way yields more
consolidation.

**Comment by bgoodri** [comment]
I think if we do function based files, then we can probably do a lot of the checking for error messages within that test file. And we are going to have to keep separate files for some things like `test_stan_functions.R`. I don't think we need to do as much testing that our function yields the "same" answers as the original function under flat priors. But we need to make sure it runs and that the likelihood we are calculating matches the likelihood at the MLE.

**Comment by bgoodri** [comment]
I am doing this today
