### ISSUE TITLE
should not error due to constant outcome when `prior_PD = TRUE`

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#337]
Users should be able to do
```
stan_glm(1 ~ x1 + x2 + ..., prior_PD = TRUE)
```
but it errors due to having a constant variable for the outcome, that is not actually being used when `prior_PD` is TRUE.

Similarly, I think
```
stan_glm( ~ x1 + x2 + ..., prior_PD = TRUE)
```
should be valid syntax but also errors.

**Comment by jgabry** [comment]
Unfortunately the outcome variable _is_ being used even when `prior_PD=TRUE`, at least for Gaussian models with default priors (priors are affected by scale of outcome). So even if we allowed this syntax it wouldn't work for Gaussian models with the default priors. 

We could certainly implement this for other cases when the outcome variable isn't used when `prior_PD=TRUE`, but do we really want to allow this if it won't even work for our most basic/canonical model (linear regression with default priors)?

**Comment by bgoodri** [comment]
I would just set the outcome standard deviation to be 1 if we need it to
construct the priors.

**Comment by jgabry** [comment]
Ok. In terms of what the syntax should look like I think we should have one official way to do this rather than trying to allow multiple ways. So let's either use `1 ~ x1 + x2 + ...` or `~ x1 + x2 + ...` but not both of them if that's alright with you. I slightly prefer the one without anything on the LHS but I don't really care which one. Preference?

**Comment by bgoodri** [comment]
I like the one-sided formula too, but y ~ x1 + x2 + ... should still be
legal even if prior_PD = TRUE.

**Comment by jgabry** [comment]
Yeah definitely
