### ISSUE TITLE
Error in loo_compare(loo_bglm_1, loo_bglm_2) : could not find function "loo_compare"

### ISSUE THREAD

**Issue by saygee** [stan-dev/rstanarm#359]
#### Summary:
When I knit the rstanarm.Rmd file on rstudio, I get an error that says: 
Error in loo_compare(loo_bglm_1, loo_bglm_2) : could not find function "loo_compare"

#### Description:
Knitting the rstanarm.Rmd file on rstudio produces the following error:

"Quitting from lines 289-290 (rstanarm.Rmd) 
Error in loo_compare(loo_bglm_1, loo_bglm_2) : 
  could not find function "loo_compare"
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
In addition: Warning messages:
1: Found 1 observation(s) with a pareto_k > 0.7. We recommend calling 'loo' again with argument 'k_threshold = 0.7' in order to calculate the ELPD without the assumption that these observations are negligible. This will refit the model 1 times to compute the ELPDs for the problematic observations directly.
 
2: Found 2 observation(s) with a pareto_k > 0.7. We recommend calling 'loo' again with argument 'k_threshold = 0.7' in order to calculate the ELPD without the assumption that these observations are negligible. This will refit the model 2 times to compute the ELPDs for the problematic observations directly.
 
3: In plot.psis_loo(loo_bglm_1, label_points = TRUE) :
  2.4% of Pareto k estimates are Inf/NA/NaN and not plotted.
4: In plot.psis_loo(loo_bglm_2, label_points = TRUE) :
  2.4% of Pareto k estimates are Inf/NA/NaN and not plotted.

Execution halted"

How do I correctly compile the rstanarm.Rmd file?

#### Reproducible Steps:
knitting the rstanarm.Rmd file on rstudio

#### RStanARM Version:
2.18.2

#### R Version:
3.5.3

#### Operating System:
Windows 10 Home version 1809 build 17763.437

**Comment by jgabry** [comment]
I think the issue is that the github version of rstanarm is ahead of the CRAN release. The `loo_compare()` method will be available in the next release (very soon) and we have updated the Rmd files for the vignettes in preparation of that. For now you would need the github version of rstanarm installed in order to build an Rmd file using `loo_compare()`. In the current CRAN release the function to use is `compare_models()` but that will be deprecated in favor of the better `loo_compare()` in the next release. 

Alternatively, if you don't want to install rstanarm from GitHub (it's slow since it pre-compiles all the models) then since the new `loo_compare()` method for rstanarm will call `loo::loo_compare()` under the hood, you could probably substitute `loo::loo_compare()` for any calls to `loo_compare()` in the Rmd file. Directly calling the version from the loo package won't be necessary once the next rstanarm is released.

**Comment by saygee** [comment]
I see. It seems it's a problem of different versions of `rstanarm` from CRAN and github. The recommendation to use `loo::loo_compare()` worked. Thanks!
