### ISSUE TITLE
installing branch rstanarm/survival gives no man pages

### ISSUE THREAD

**Issue by padpadpadpad** [stan-dev/rstanarm#426]
When I run `remotes::install_github('stan-dev/rstanarm@feature/survival')`, no man pages are installed alongside the package. The package does however install ok. I get the message `no man pages found in package`. Accessing the specific man pages for that version of rstanarm would be super helpful.

When I install rstanarm from CRAN this problem does not occur. 

I am running R v3.6.1 and macOS Mojave 10.14.6.

**Comment by sambrilleman** [comment]
@padpadpadpad 
@bgoodri Do you know an easy way to resolve this? I've had a quick google and can't see the option in `install_github` to build documentation using **roxygen** as part of the install.

@padpadpadpad The issue is that the documentation is built using **roxygen**.

If we don't have a way to install documentation using **roxygen** as part of the package install, then alternatively, my usual workflow is:

1. clone the survival branch to my local machine
2. open the R project (i.e. [rstanarm.Rproj](https://github.com/stan-dev/rstanarm/blob/master/rstanarm.Rproj) in the root directory of the repo) in RStudio
3. go to the "Build" tab in Rstudio
4. click `More > Configure Build Tools` and tick "Generate documentation with roxygen" and then tick "Automatically roxygenise when running: Install and Restart"
5. click "Install and Restart" under the Build tab in RStudio

Note that sometimes I have to click "Install & Restart" once with "Generate documentation with roxygen" **unticked** to build the package and then after that click "Install & Restart" with "Generate documentation with roxygen" **ticked** to build the docs. If I try and install the package and build the docs at the same time then I get a compiler error. It's some issue with roxygen I think, but might be ok for Mac or fixed in the latest version of **roxygen** anyway. But thought I'd mention just in case.

Ideally you can avoid all this though if there is a way to use `install_github` with documentation build using **roxygen**.

**Comment by padpadpadpad** [comment]
Hi Sam

This works but only after running `devtools::document()` as the man pages are not rendered on the survival branch to begin with.

**Comment by sambrilleman** [comment]
Awesome, thanks for sharing the solution! I will try and add this to the instructions when I finally get around to adding them to the arXiv paper (haven't got to doing that yet!)
