### ISSUE TITLE
Incorrect predictions with alternative contrasts

### ISSUE THREAD

**Issue by rvlenth** [stan-dev/rstanarm#444]
#### Summary:
If a model is fitted with manually specified contrast coding that differs from `getOption("contrasts")`, incorrect predictions are obtained with new data.

#### Description:
See example below. Looking at the code for `predict.stanreg`, it appears that the internal function `pp_data` does not use the user-specified contrasts. I discovered this via an issue in the **emmeans** package: https://github.com/rvlenth/emmeans/issues/212 -- I had borrowed some code from `predict.stanreg` to make my package support more models.

#### Reproducible Steps:
```r
library("rstanarm")
m1 <- stan_glm(breaks ~ wool * tension, data = warpbreaks,
               prior = rstanarm::student_t(3, 0, 3, autoscale = FALSE), 
               contrasts = list(wool = "contr.sum", tension = "contr.sum"))
predict(m1)
##       1        2        3        4        5        6        7        8        9       10 
## 40.05105 40.05105 40.05105 40.05105 40.05105 40.05105 40.05105 40.05105 40.05105 26.67657 

predict(m1, newdata = warpbreaks[1:3, ])
##       1        2        3 
## 28.10021 28.10021 28.10021 
```
The first 3 predictions should match, but they don't.

#### RStanARM Version:
2.19.3

#### R Version:
4.0.1

#### Operating System:
Windows 10

**Comment by jgabry** [comment]
Sorry for the slow reply! I should have a fix for this in a few minutes. 

When debugging this I noticed that `object$contrasts` is `NULL` here: 

https://github.com/stan-dev/rstanarm/blob/9155385c2a8a78a36ae3fe6568d3994098386d7e/R/pp_data.R#L65

so that's the problem. I traced this back to one of those annoying R issues where subsetting drops relevant attributes. In `stan_glm()` we have 

https://github.com/stan-dev/rstanarm/blob/9155385c2a8a78a36ae3fe6568d3994098386d7e/R/stan_glm.R#L238

which works fine and has the right contrasts. However, before returning the object we have 

https://github.com/stan-dev/rstanarm/blob/9155385c2a8a78a36ae3fe6568d3994098386d7e/R/stan_glm.R#L275

which is correct except for the fact that it drops the contrasts attribute!

**Comment by jgabry** [comment]
Just opened a PR to fix this: https://github.com/stan-dev/rstanarm/pull/459
