### ISSUE TITLE
Turn of centering of variables

### ISSUE THREAD

**Issue by alexandrahotti** [stan-dev/rstanarm#453]
Description:
How would I turn off centering of the variables if I am using stan_glm() with specific normal priors specified for prior_intercept and each regression parameter?

# UPDATE 1:
I found this description but I did not completely get it:

"To disable the centering of the predictors, you need to omit the intercept from the model formula and include a column of ones as a predictor (which cannot be named "(Intercept)" in the data.frame). Then you can specify a prior “coefficient” for the column of ones"

I assume it means that I should remove prior_intercept() from stan_glm() and instead put the intercept prior on the ones column?

This is my code: (Where ones is a vector of ones)

```
  poisson.model.stan <- stan_glm(N~ log(a) + n + log(k) +log(d)+ones , 
                               family = poisson(link=log), data=data ,offset=log(duration),
                               prior=normal(location  = c(p1, p2, p3, p4, p5), 
                                scale= c(v1, v2, v3, v4, v5), autoscale = FALSE))

```

# UPDATE 2:
When I try the above, I get the following error:
```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: mismatch in dimension declared and found in context; processing stage=data initialization; variable name=prior_scale; position=0; dims declared=(4); dims found=(5)  (in '/data/hyperparameters.stan' at line 2; included from 'model_count' at line 19)

In addition: Warning message:
In center_x(x, sparse) : Dropped empty interaction levels: ones
failed to create the sampler; sampling not done
Error in check_stanfit(stanfit) : 
  Invalid stanfit object produced please report bug
```

RStanARM Version:

‘2.19.2’

R Version:

‘3.6.2’

Operating System:

Windows 10

**Comment by jgabry** [comment]
I think when you add `ones` you also need to add `0` to the formula, which is R's way of indicating to omit the intercept (which you need here since it's replaced by `ones`). So in your case, it would be 

```
N ~ 0 + ones + log(a) + n + log(k) +log(d)
```

Does that work or does it still give you that error?

**Comment by alexandrahotti** [comment]
@jgabry thank you! The error seems to have disappeared. How would I specify the corresponding prior for that formula?
I want to specify a unique normal prior for each regression parameter and the intercept.

**Comment by jgabry** [comment]
Glad that fixed the error. Regarding the priors, only the intercept is affected by the centering, so you can use the same prior that you have for the coefficients (the `prior` argument). That's because centering predictors doesn't change any slopes, it only shifts things. For the prior on the intercept (`prior_intercept` argument) that will have a different interpretation now. Here's how to think about the `prior_intercept` argument depending on whether you're using a regular formula or using `~ 0 + ones` (below I'm using y and x to generically refer to the outcome and predictors, respectively): 

* If using a standard formula then `prior_intercept` refers to the value of `y` when `x` is at its average value (so `prior_intercept` is what do you think `y` is when `x = mean(x)`?) 

* If using `~ 0 + ones` in the formula, then the intercept refers to the value of `y` when `x` is 0 (so `prior_intercept` is what do you think `y` is when `x = 0`) 

Does that make sense? 

Also, just like for the `prior` argument you might want to use `autoscale=FALSE` when specifying the `prior_intercept` argument since you're using rstanarm 2.19.2 (in the latest release this isn't necessary anymore).

**Comment by alexandrahotti** [comment]
@jgabry Sorry, I was a bit unclear in my question. What I meant to ask was whether I have to change the argument:
```
prior=normal(location  = c(p1, p2, p3, p4, p5), 
                                scale= c(v1, v2, v3, v4, v5)

N ~ 0 + ones + log(a) + n + log(k) +log(d)
```
more specifically, would p1 be assigned to the 0, p2 to ones, p3 to log(a), p4 to n, and so on. Or does the code know to "skip" the zero?

Thanks for the gr8 replies!

**Comment by jgabry** [comment]
Oh I see. Actually rereading your post you were clear and I actually just gave you the wrong info! I confused myself for a second. You don't need a `prior_intercept` argument at all, since the intercept is now the `ones` column and controlled via `prior` like the other coefficients. And yeah it should know to skip the zero. So if you have 

```r
N ~ 0 + ones + log(a) + n + log(k) +log(d)
``` 

which has 5 terms on the right-hand side (including 0), you only need 4 elements in the vectors you pass to `normal()`. The first element will refer to `ones` the second to `log(a)`, etc.
