### ISSUE TITLE
algorithm="optimizing" not selectable

### ISSUE THREAD

**Issue by masanao-yajima** [stan-dev/rstanarm#475]
#### Summary:
In Rstanarm functions, because "optimizing" is not in the list of option for the algorithm parameter one cannot select it.  algorithm = c("sampling",  "meanfield", "fullrank")

#### Description:
If you look into the function definition, the algorithm parameter has fixed options algorithm = c("sampling",  "meanfield", "fullrank"), which does not allow one to use the "optimizing" option.

#### Reproducible Steps:
> stan_lm(1~1,algorithm = "optimizing")
Error in match.arg(algorithm) : 
  'arg' should be one of “sampling”, “meanfield”, “fullrank”

#### RStanARM Version:
The version of the rstanarm package you are running (e.g., from `packageVersion("rstanarm")`)

#### R Version:
‘4.0.2’
 rstanarm version 2.21.1

#### Operating System:
OS X 10.14.6

**Comment by jgabry** [comment]
Yeah, the optimization algorithm is only available for a subset of the modeling functions. For example it should be selectable with `stan_glm()`, but not `stan_lm()`. I forget why it's not enabled for `stan_lm()` in particular, but probably something to do with the unique prior used by `stan_lm()` making it not amenable to optimization. In other cases like `stan_glmer()` it's not enabled because optimization will fail for hierarchical models. But it should work fine with `stan_glm()`.

**Comment by masanao-yajima** [comment]
Got it.  It was one of this case. "NOTE: not all fitting functions support all four algorithms."  Thanks.

**Comment by jgabry** [comment]
Thanks for following up!
