### ISSUE TITLE
Document refresh=0 better

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#476]
A lot of people want to suppress the iteration output (for example, https://discourse.mc-stan.org/t/controlling-stan-glm-output/18708) but how to do that isn't documented well. Right now it's part of `...` which gets passed to RStan, however if you follow the trail to the RStan documentation then you find that there's no explicit `refresh` argument either, it's actually part of `...` there also. So we should either mention `refresh=0` more prominently in the doc or make it an explicit argument like we did with `adapt_delta`.

**Comment by sambrilleman** [comment]
Great idea. I am using Python quite a bit these days and the problem is even worse. They use `kwargs` everywhere (essentially equivalent to `...`) and you can follow the trail of `kwargs` ten functions deep and still never find the documentation for the argument you are looking for. Drives me absolutely mental. 😖

**Comment by jgabry** [comment]
Wow yeah that sounds infuriating!

**Comment by jgabry** [comment]
I added a note specifically about `refresh` to the documentation for `...`: 

https://github.com/stan-dev/rstanarm/blob/bce6799fe27eedfa94951b79c15d19cf6027e709/man-roxygen/args-dots.R#L9-L12
