### ISSUE TITLE
rstanarm throwing error when applied to estimation of negative binomial model in ROS book (ch15 ex1)

### ISSUE THREAD

**Issue by edhearn84** [stan-dev/rstanarm#494]
#### Summary:
Negative binomial model crashes out when applied to Risky data on HIV infection

#### Description:
Code keeps throwing this error:

"error occurred during calling the sampler; sampling not done
Error in check_stanfit(stanfit) : 
  Invalid stanfit object produced please report bug"

Poisson regressions in parts a and b of Ch 15, Ex1 run fine, if run prior to to negative binomial. But, once negative binomial errors out, the Poisson regressions won't run either. 

#### Reproducible Steps:
neg_bin = stan_glm(bupacts ~ women_alone , data = risky , family = neg_binomial_2(link = "log"))

After application to Gelman's Risky ROS data. 

#### RStanARM Version:
RStanArm Version 2.19.2

#### R Version:
R Version 3.6.2

#### Operating System:
Mac OS Catalina Version 10.15.5

**Comment by jgabry** [comment]
Hi @edhearn84, thanks for reporting this. I'm not able to reproduce this on my Mac with Catalina 10.15.5 (it runs fine for me), but I have R 4.0.3 and rstanarm 2.21.1 and it looks like you have older versions of both. I think it _should_ work with your versions, but since it's not working I would guess that updating both would fix the problem. Either way I recommend updating R and rstanarm because we made some other changes specifically to line up with the content of Regression and Other Stories. So even if you weren't getting an error there would differences between your version and what the book is expecting (e.g. some changes to priors, the new `posterior_epred()` function, and a few other things).

**Comment by edhearn84** [comment]
Hello @jgabry, no problem. I'm also happy to report that your suggestion worked like a charm: updates to both R and rstanarm (via CRAN) solved my issues! Thanks for your prompt response and good advice

**Comment by jgabry** [comment]
> I'm also happy to report that your suggestion worked like a charm: updates to both R and rstanarm (via CRAN) solved my issues! Thanks for your prompt response and good advice

Ok great, glad that worked! Thanks for letting me know.
