### ISSUE TITLE
could not find function "stan_surv" from developer version

### ISSUE THREAD

**Issue by liboliba** [stan-dev/rstanarm#500]
#### Summary:
could not find function "stan_surv" from development version of the rstanarm 

#### Description:
Hello there,
I manage to install a "fresh" R4.0.3, devtools and the development version of the rstanarm from this github. These installation steps seem to be fine. 
When I run the rstanarm package, it could not find function "stan_surv". but I never install the CRAN version of the rstanarm  before myself.

Thank you for your advise,
Regards
Libo 

#### Reproducible Steps:
> library(rstanarm)
Loading required package: Rcpp
This is rstanarm version 2.21.2
- See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
- Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
- For execution on a local, multicore CPU with excess RAM we recommend calling
  options(mc.cores = parallel::detectCores())
> library(survival)
> kfit <- coxph(Surv(time, status)~ age + sex + disease, kidney)
> fit1<-stan_surv(Surv(time, status)~ age + sex + disease, kidney)
Error in stan_surv(Surv(time, status) ~ age + sex + disease, kidney) : 
  could not find function "stan_surv"

#### RStanARM Version:
> packageVersion("rstanarm")
[1] ‘2.21.2’

#### R Version:
Rx64, 4.0.3

#### Operating System:
Windows 10

**Comment by sambrilleman** [comment]
Hi, you probably need to install the `feature/survival` branch from GitHub, not `master` branch. Sorry for the confusion.

In any case it is easier to install the binary using 

```
install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

as discussed at the bottom of this thread: https://discourse.mc-stan.org/t/rstanarm-cran-vs-development-version-installation-issues/14399/35

Hope that helps!

**Comment by liboliba** [comment]
> Hi, you probably need to install the `feature/survival` branch from GitHub, not `master` branch. Sorry for the confusion.
> 
> In any case it is easier to install the binary using
> 
> ```
> install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
> ```
> 
> as discussed at the bottom of this thread: https://discourse.mc-stan.org/t/rstanarm-cran-vs-development-version-installation-issues/14399/35
> 
> Hope that helps!

Works like a charm and thanks for the link provided. 
Happy new year!

**Comment by sambrilleman** [comment]
Glad it worked! 😀

**Comment by mollymcentee** [comment]
I'm having this same problem, even after using:

install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))


I installed rstan and that seems to be working, but when I try to use stan_surv, it says it can't find the function:

library(survival)
kfit <- coxph(Surv(time, status)~ age + sex + disease, kidney)
fit1<-stan_surv(Surv(time, status)~ age + sex + disease, kidney)

Error in stan_surv(Surv(time, status) ~ age + sex + disease, kidney) :
could not find function "stan_surv"

**Comment by sambrilleman** [comment]
Perhaps you need `library(rstanarm)`?

**Comment by mollymcentee** [comment]
Sorry, what I wrote was confusing! I did call library(rstanarm), here's the code and messages I've gotten: 

```
install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))

library(rstanarm)

Loading required package: Rcpp
Registered S3 methods overwritten by 'htmltools':
  method               from         
  print.html           tools:rstudio
  print.shiny.tag      tools:rstudio
  print.shiny.tag.list tools:rstudio
Registered S3 method overwritten by 'htmlwidgets':
  method           from         
  print.htmlwidget tools:rstudio
This is rstanarm version 2.21.3
- See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
- Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
- For execution on a local, multicore CPU with excess RAM we recommend calling
  options(mc.cores = parallel::detectCores())


library(survival)
kfit <- coxph(Surv(time, status)~ age + sex + disease, kidney)
fit1<-stan_surv(Surv(time, status)~ age + sex + disease, kidney)

Error in stan_surv(Surv(time, status) ~ age + sex + disease, kidney) :
could not find function "stan_surv"
```

I tried some other functions from rstanarm and they seem to be working fine; this code runs with no errors:

```
mtcars$mpg10 <- mtcars$mpg / 10

fit <- stan_glm(
  mpg10 ~ wt + cyl + am,            
  data = mtcars, 
  QR = TRUE,
  # for speed of example only (default is "sampling")
  algorithm = "fullrank",
  refresh = 0 
 ) 
```

Since the other functions are working, I thought it might be an issue with installing the correct branch from github, but when I try this:

```
remove.packages("rstanarm")

gh_install_packages("rstanarm", ref = "feature/survival")

```

I get a long error message that ends with: ERROR: compilation failed for package ‘rstanarm’.

Is there another way I should try installing? Thanks!

**Comment by sambrilleman** [comment]
Hmm, I think installing direct from Github is problematic for many people because it needs to compile the package.

But, installing from the https://mc-stan.org/r-packages/ repository should just install a binary, so much easier.

As to why it is a binary without `stan_surv` I'm not sure. I thought that hosted version was the survival version, last I knew. But I did try installing it at my end too, and I think you are right. The binary hosted at https://mc-stan.org/r-packages/ might not include `stan_surv`. Perhaps @rok-cesnovar or @jgabry knows - has the binary there been updated to a version without `stan_surv`?

**Comment by mollymcentee** [comment]
Thanks for looking into this!

In the meantime, I'm trying to install from github, and posted the error messages I'm getting here : https://discourse.mc-stan.org/t/error-installing-rstanarm-from-github/28138

Any insight would be much appreciated!

**Comment by maurosc3ner** [comment]
> Hmm, I think installing direct from Github is problematic for many people because it needs to compile the package.
> 
> But, installing from the https://mc-stan.org/r-packages/ repository should just install a binary, so much easier.
> 
> As to why it is a binary without `stan_surv` I'm not sure. I thought that hosted version was the survival version, last I knew. But I did try installing it at my end too, and I think you are right. The binary hosted at https://mc-stan.org/r-packages/ might not include `stan_surv`. Perhaps @rok-cesnovar or @jgabry knows - has the binary there been updated to a version without `stan_surv`?

Hi, 

Any update about this? I have also try to reinstall it using advice from here and discourse but having same issue (stan_surv is not recognized). High probabilities that mc-discource binary does not have stan_surv branch in it.

Is there sources option to compile it?

Thanks

**Comment by cbonsig** [comment]
As of July 25 2022, I found that the binary on Github did not include stan_surv
```
# this does not include stan_surv
# install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

I successfully installed from source with:
```
install.packages("devtools")
devtools::install_github("stan-dev/rstanarm",ref = "feature/survival", build_vignettes = FALSE)
```

Excerpt from sessionInfo()
```
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.4

other attached packages:
 [1] rstanarm_2.21.2 Rcpp_1.0.9
```

**Comment by flow-pow** [comment]
Hi, any more updates? I need to use the stan_surv() function and still no luck after following advice above. thanks.

**Comment by sambrilleman** [comment]
So I don't think I can help at the moment with problems building the package from source (e.g. using `install_github`) since I've not tried that out myself with latest versions of R.

But... I think I may have at least worked out why the binary installed from https://mc-stan.org/r-packages/ (as per the Github README instructions) seems to be excluding `stan_surv` for so many people. The instructions say to use:

```
install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

but that command includes a vector of repos, and the `getOption("repos")` likely includes the CRAN mirror as a fallback. So, if it fails to install rstanarm from the mc-stan repo, then it likely falls back to the CRAN version of rstanarm, which doesn't include `stan_surv`. The reason it has probably started failing to install the binary for so many people is that I think that mc-stan repo only includes a Windows binary for R 4.0 !! ☹️ It perhaps hasn't had binaries pushed for R 4.2 (latest) or even perhaps 4.1... see https://github.com/stan-dev/r-packages/tree/gh-pages/bin/windows/contrib

I'm not actively working on this stuff anymore, so have no idea whether the `feature/survival` branch can be easily built with R 4.2, but it sounds like from this thread that @cbonsig at least did it successfully on Mac. So hopefully we can, in principle, get binaries built for the latest R (and perhaps also R 4.1). But I think I'd need help from someone - perhaps @rok-cesnovar to try and do that and get them hosted on mc-stan.org.

If however you downgrade to R 4.0 (e.g. R 4.0.5) and try run `install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/"))` (after installing the necessary dependencies) then you will get the binary hosted at mc-stan.org that includes `stan_surv` (i.e. the host binary that people were successfully using until recently). But it's also worth noting that the mc-stan.org binary unfortunately doesn't include the docs with it, so running `?stan_surv` isn't a reliable check. You are better to run an example model, e.g. something like

```
library(rstanarm)
m2 <- stan_surv(Surv(l, u, type = "interval2") ~ grp, data = mice, chains = 1, refresh = 0, iter = 600)
```

I realise this post doesn't actually provide a good solution, and I'm sorry about that. But hopefully it will at least help some people debug what might be going on with their installation problem(s).

**Comment by maurosc3ner** [comment]
> As of July 25 2022, I found that the binary on Github did not include stan_surv
> 
> ```
> # this does not include stan_surv
> # install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
> ```
> 
> I successfully installed from source with:
> 
> ```
> install.packages("devtools")
> devtools::install_github("stan-dev/rstanarm",ref = "feature/survival", build_vignettes = FALSE)
> ```
> 
> Excerpt from sessionInfo()
> 
> ```
> R version 4.2.0 (2022-04-22)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Monterey 12.4
> 
> other attached packages:
>  [1] rstanarm_2.21.2 Rcpp_1.0.9
> ```

Hi, 
After a clean installation on my windows machine I have been able to install rstanarm (sources)+mice example tested. Hoping this package will be included in the binaries any time soon?

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)
other attached packages:
[1] rstanarm_2.21.2 Rcpp_1.0.9  
```

   
Thanks all!
Esteban
