### ISSUE TITLE
stan_jm vignette hard-codes results 

### ISSUE THREAD

**Issue by wlandau** [stan-dev/rstanarm#504]
#### Summary:

The joint modeling vignette hard-codes a result in a way that makes it difficult to understand where to look for the association parameter in the output.

#### Description:

From [here in the vignette](https://github.com/stan-dev/rstanarm/blob/dee0a2d45bf42b2df791072041151b753edd6af9/vignettes/jm.Rmd#L535):

> The output tells us that for each one unit increase in an individual’s underlying level of log serum bilirubin, their estimated log hazard of death increases by 35.1% (equivalent to a 3.86-fold increase in the hazard of death).

However, in the [rendered output](http://mc-stan.org/rstanarm/articles/jm.html#fitting-the-models-1), `Long1|etavalue` has a median of 1.340 (under "event submodel") and `Assoc|Long1|etavalue` has a mean of 1.347, neither of which is the expected 1.351. This minor discrepancy makes me unsure if I am really looking in the right place for the association parameter estimates.

**Comment by wlandau** [comment]
I am also realizing I may not understand the interpretation. If `alpha` is estimated to be 1.34 for the current value association structure, then for every increase in one unit of `logBili`, the log hazard goes up by 1.34, and the hazard gets multiplied by exp(1.34) = 3.82. But this is agnostic to the fixed value of log hazard we start with before the hypothetical unit increase in `logBilli`. So can we really claim to talk about percentage increase?

**Comment by sambrilleman** [comment]
> if `alpha` is estimated to be 1.34, then for every increase in one unit of `logBili`, the log hazard increases by 1.34, and the hazard gets multiplied by exp(1.34) = 3.82. But this is agnostic to the fixed value of log hazard we start with for the hypothetical unit increase in `logBilli`.

You are correct!

> their estimated log hazard of death increases by 35.1%

Woops, I think this is a typo! You are right, it should be something like "their estimated log hazard of death increases by 1.35", not 35%!

The percentage / relative increase is for the hazard, not the log hazard.

> equivalent to a 3.86-fold increase in the hazard of death

So this bit is correct -- i.e. a relative increase in the hazard.

> `Long1|etavalue` has a median of 1.340 (under "event submodel") and `Assoc|Long1|etavalue` has a mean of 1.347, neither of which is the expected 1.351. This minor discrepancy makes me unsure if I am really looking in the right place for the association parameter estimates.

You are looking in the right place, but like you say, the results in the text are hardcoded and therefore probably are no longer consistent between the text and the output since the seed might have worked differently for different versions of R or something.

We should probably render the value in the text based on the output, and not hardcode it in text. Please feel free to open a PR with that if you know how to do it! 😀

**Comment by wlandau** [comment]
Thank you so much for checking my understanding, @sambrilleman. I am using `stan_jm()` for an important project at work, and I mainly wanted to make sure I was drawing accurate conclusions.

I would be happy to put together a PR. I hope to get to it later this week or early next week.

**Comment by wlandau** [comment]
Related question: what is your overall sense of the uptake of Bayesian joint modeling in general and `stan_jm()` in particular? Have you observed widespread usage in applied scenarios?

**Comment by sambrilleman** [comment]
> Related question: what is your overall sense of the uptake of Bayesian joint modeling in general and `stan_jm()` in particular? Have you observed widespread usage in applied scenarios?

Hi @wlandau, I'm not too sure in particular about uptake, especially now since I am outside of academia and have been for the last 12-18 months. Prior to that, most of my reading was of methodology JM papers, of which a large proportion took a Bayesian approach. Not too sure about in the applied world though.

It was interesting to see a few years ago that Dimitris Rizopoulos stopped adding features to his `JM` package, which was probably one of the most widely used joint modelling packages at the time, and decided that any new features would only be added to his `JMBayes` package. Partly due to some lessons he learnt from the `JM` implementation I think (perhaps making it harder to extend), and also because some of the more advanced joint modelling extensions are only possible, or at least easier, in a Bayesian framework. I imagine that helped nudge along Bayesian joint modelling in the applied world too.

I don't have a good gauge on the uptake of `stan_jm` either unfortunately. I've not been keeping an eye on citations for example, and even then, that probably isn't too reliable a gauge for the actual uptake of the software anyway.
