### ISSUE TITLE
Truncated priors in (g)lm(er) models?

### ISSUE THREAD

**Issue by joelgombin** [stan-dev/rstanarm#58]
Are there plans to implement the possibility of including truncated priors (for beta coefficients, or even intercept) in (g)lm(er) models, through beta or uniform distributions?

**Comment by bgoodri** [comment]
There are no plans to do so, and actually the plan is not to do so. We are trying to promote best practices with rstanarm, and in general, we think the best practice is to impose inequality restrictions only when they are logically necessary (i.e. standard deviations must be positive, correlations must be between -1 and 1, etc.). 

For a beta prior with both shape parameters greater than 1, you can get almost the same posterior with a normal prior whose mean and standard deviation match that of the beta prior. It is harder to approximate a uniform prior with finite a and b, but also harder to get good sampling from Stan because any realizations that are close to b are close to infinity in the unconstrained space. 

All that said, there are perhaps some situations where such priors are warranted, but we are content to say that in those situations, users should just write their own Stan programs and call them via the `stan()` or `sampling()` functions in the rstan package.

**Comment by joelgombin** [comment]
Understood! Indeed goign back to `rstan` makes sense for rare usecases.
