### ISSUE TITLE
Error: One-dimensional unit vector is discrete

### ISSUE THREAD

**Issue by invertdna** [stan-dev/rstanarm#603]
#### Summary:
updated stan_lm() is throwing an error for a straightforward linear model with continuous/numeric response and predictor variables. 

#### Description:

Full error is: 
```
Error : Exception: Found dimension size one in unit vector declaration. One-dimensional unit vector is discrete but the target distribution must be continuous. variable=u; dimension size expression=K (in 'lm', line 74, column 35 to column 36)
failed to create the sampler; sampling not done
Error in check_stanfit(stanfit) : 
  Invalid stanfit object produced please report bug
```

#### Reproducible Steps:

```
x <- rnorm(100, 0, .1)
y <- rnorm(2.3*x + 10, .5)
b <- data.frame(x, y)
stan_lm(y ~ x, data = b, prior = NULL)

```

#### RStanARM Version:
2.26.1

#### R Version:
4.3.1

#### Operating System:
OS X 13.3.1

**Comment by jgabry** [comment]
@bgoodri Can you take a look at this? It's also breaking some code from Regression and Other stories (see below for more details). 

@invertdna Thanks for reporting this. I think this is a bug introduced with the latest update when we switched to using Stan 2.26. This happens when there's only 1 predictor (it should work fine if you add another variable on the RHS of the formula) when using `stan_lm` or `stan_polr`.

@bgoodri any idea why this fails with 2.26? This causes some of the examples from Regression and Other Stories to error that used to run fine. For example, this `stan_polr` code from ROS now errors with 2.26 because it only has 1 predictor:

https://github.com/avehtari/ROS-Examples/blob/a049a1044aef17bb90664d3b4735fc7ad6ff5575/Storable/storable.Rmd#L54-L55

The unit vector array in `polr.stan` is declared with 

```stan
array[K > 1] unit_vector[K] u;
```

so if there's only 1 predictor (K=1) it would be `array[0] unit_vector[0] u`. But I don't see why that should be a problem since it's only used in transformed parameters if `K > 1` and it used to be fine in earlier versions. Also the error message says that the `target distribution must be continuous`, which doesn't seem relevant here:  

```
Exception: Found dimension size one in unit vector declaration. 
One-dimensional unit vector is discrete but the target distribution 
must be continuous. variable=u; dimension size expression=K 
```

**Comment by jgabry** [comment]
The solution may be 

```
array[K > 1] unit_vector[K > 1 ? K ? 2] u;
```

which makes it size 2 when K=1 (it won't even get used so we can just do this to avoid error when K=1)
