### ISSUE TITLE
Darker line at 0 for stan_plot

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstanarm#70]
Since most applied researchers are focused on p-values and refuse to look as intervals, I would like to help them a bit reading when stan_plot reading.

It would be nice if the v=0 line could be a bit darker in the grid. I know, I can override it in the plot, so this is a bit of luxury.

**Comment by jgabry** [comment]
I don't want to always encourage people to focus on whether the 95%
interval includes 0 because that's basically like looking at p-values, but
I do think it's often useful to highlight where 0 is.

What about instead of always highlighting 0 in every plot (it's conceivable
that some plots won't even show 0 although most will if variables are on
reasonable scales) we add some convenience functions for adding common
things to plots? For example

plot(fit, ci_level=0.8) + highlight_zero()

or something like highlight_value(value) with the default being 0, so
people don't need to call geom_vline There are probably many other similar
convenience functions that would be useful.

**Comment by dmenne** [comment]
Great! Best of two world, and no digging for special grid.

**Comment by dmenne** [comment]
>>I don't want to always encourage people to focus on whether the 95%
interval includes 0 because that's basically like looking at p-values, but
I do think it's often useful to highlight where 0 is.>>

 

Point taken and well said. If only I could convince my medical researchers and reviewers. It’s hard enough.

 

Dieter

**Comment by jgabry** [comment]
I haven't forgotten about these plotting issues! Working on a package that will serve as a back-end for most of the plotting functionality in Stan-related R packages, so once that's ready and hooked up with rstanarm I'll come back to issues like this one if they're not already taken care of by the plotting package.

**Comment by jgabry** [comment]
This is possible now with the functions in the stan-dev/bayesplot repository, which will soon be used as the backend for plotting in rstanarm (and other packages). I'm closing this issue here as it's no longer an rstanarm issue. If there's more to discuss on this issue let's do it over at the [bayesplot repo](https://github.com/stan-dev/bayesplot).
